import random
def random_prompt():    
    prompts = [
        "Robot",
        "Skull",
        "Dragon",
        "Fox",
        "Whale",
        "Mushroom",
        "Sword",
        "Helmet",
        "Lantern",
        "Spider",
        "Jellyfish",
        "Shark",
        "Dinosaur",
        "Turtle",
        "Camera",
        "Bicycle",
        "Clock",
        "Moon",
        "Planet",
        "Mask",
        "Candle",
        "Potion",
        "Guitar",
        "Book",
        "Key",
        "Crown",
        "Apple",
        "Banana",
        "Frog",
        "Snake",
        "Octopus",
        "Crab",
        "Fish",
        "Owl",
        "Penguin",
        "Cat",
        "Dog",
        "Bat",
        "Ghost",
        "Rocket",
        "Spaceship",
        "Alien",
        "Robot arm",
        "Drone",
        "Train",
        "Castle",
        "Tower",
        "Volcano",
        "Cloud",
        "Star",
        "Crystal",
        "Gem",
        "Coin",
        "Treasure chest",
        "Hammer",
        "Axe",
        "Bow",
        "Arrow",
        "Shield",
        "Boots",
        "Backpack",
        "Chair",
        "Lamp",
        "Window",
        "Door",
        "Mirror",
        "Vase",
        "Flower",
        "Tree",
        "Leaf",
        "Acorn",
        "Feather",
        "Shell",
        "Ice cream",
        "Pizza",
        "Burger",
        "Coffee cup",
        "Teapot",
        "Bottle",
        "Dice",
        "Chess piece",
        "Rubik cube",
        "Arcade machine",
        "Headphones",
        "Keyboard",
        "Mouse",
        "Phone",
        "TV",
        "Radio",
        "Cassette tape",
        "Vinyl record",
        "Skateboard",
        "Airplane",
        "Submarine",
        "UFO",
        "Satellite",
        "Meteor",
        "Tornado",
        "Tent",
        "Campfire",
        "Scarecrow",
        "Statue",
        "Skeleton",
        "Zombie",
        "Knight",
        "Wizard",
        "Ninja",
        "Pirate",
        "Cowboy",
        "Samurai",
        "Clown",
        "Angel",
        "Devil",
        "Phoenix",
        "Unicorn",
        "Mermaid",
        "Compass",
        "Hourglass",
        "Lock",
        "Chain",
        "Snowman",
        "Snowflake",
        "Lightning bolt",
        "Mountain",
        "Island",
        "Bridge",
        "Cave",
        "Treehouse",
        "Lighthouse",
        "Waterfall",
        "River",
        "Ship",
        "Anchor",
        "Barrel",
        "Wagon",
        "Crystal ball",
        "Magic wand",
        "Scroll",
        "Cauldron",
        "Bone",
        "Eyeball",
        "Teeth",
        "Heart",
        "Brain",
        "Glove",
        "Scarf",
        "Sunglasses",
        "Watch",
        "Ring",
        "Necklace",
        "Mug",
        "Bowl",
        "Spoon",
        "Fork",
        "Cake",
        "Donut",
        "Pretzel",
        "Taco",
        "Hotdog",
        "Pancakes",
        "Sushi",
        "Ramen bowl",
        "Cupcake"
    ]
    return prompts[int(random.random() * len(prompts))]
